### ISSUE TITLE
What is the development status of this project?

### ISSUE THREAD

**Issue by CNG** [slackhq/python-rtmbot#98] opened 2019-12-09 23:50 UTC
Hello, does Slack plan to continue development?

I need to extend the functionality and would like to know whether I should:

1. not change rtmbot code because a major revision is coming, which would potentially make my upgrade path difficult.
2. make my changes such that that they could be considered as pull requests here.

I have been trying hard to do 1, but my own code is getting more twisted trying to not modify RTMBot itself. I would be happy to do 2, but that's a lot more work, so if no further work is planned here anyway, I would more save time and just fork this project internally.

Thanks!

**Comment by alindl** [comment] 2020-04-16 13:39
Dude, I get what your are going through or went through. How did you deal with it? Please tell me you forked and updated it. What I hate most is that they use a very old version of the python `slackclient` (even though they are the developers of the `slackclient` themselves lol)

**Comment by CNG** [comment] 2020-04-16 18:54
@alindl I was waiting for a response here up until last week, when I decided to pull the `rtmbot` code into the code we have that uses it so I can at least get rid of our hacky code that works around `rtmbot` being an external library... that code is bigger than `rtmbot` itself!

I haven't yet considered how best to share back any enhancements because I was hoping Slack would provide some direction on whether this library will be updated to Python 3 and the latest `slackclient` as you mentioned. I can see potential for sharing both core bot enhancements as well as plugins that might be less business specific. For the former, I think I can at least share now this docstring that summarizes the primary use cases for our "hacks" (even involving some runtime patching of functions so I be somewhat DRY..):

> This module modifies the stock `rtmbot.RtmBot` and `rtmbot.Plugin` classes to:
> 
> * Process messages that change properly.
> 
>     `RtmBot._start` has a loop that potentially parses multiple messages
>     before sending the responses. This means we can't easily track the
>     timestamps for each response and associate it with the triggering message.
>     We could try to store the response text along with the time
>     and guess which responses corresponds to a changed or deleted message.
> 
>     Or what we did here is patch `RtmBut.output` so we can get access to
>     the `output` object from a new generic send function.
> 
> * Suppress sending and deleting messages when `--dry-run` enabled.
> 
> * Add Prometheus instrumentation:
>     * Duration histograms for:
>         * `operation_duration_seconds`, the core operations: `send`, `receive`, `delete`
>             * labels: `operation`, `type`, `subtype`
>         * `plugin_duration_seconds`, the core `do` function of the `Plugin` class
>             * labels: `plugin`, `event`, `status`
> 
>     The label `status` will be set on any event that triggers a `process_*`
>     function (such as `process_message`). This is set to `500` if the plugin
>     throws an exception, otherwise it is `204` when no content is produced
>     (which is always the case when the plugin's condition is not met) and `201`
>     when content is created. These are configured in `prometheus.py`:
> 
>         STATUS = {"no_content": 204, "created": 201, "internal_server_error": 500}

**Comment by aoberoi** [comment] 2020-04-27 21:48
Hey folks, I apologize for us not responding to this thread sooner. We need to more clearly communicate what you should expect from this package and us as maintainers.

I've started a discussion with the rest of the maintainers to help get you some answers. I hope to drive that to some decisions that I can share before the end of this week.

Thanks for your patience.

**Comment by alindl** [comment] 2020-05-30 15:34
> Hey folks, I apologize for us not responding to this thread sooner. We need to more clearly communicate what you should expect from this package and us as maintainers.
> 
> I've started a discussion with the rest of the maintainers to help get you some answers. I hope to drive that to some decisions that I can share before the end of this week.
> 
> Thanks for your patience.

Sorry, but "the end of this week" was over a month ago. Any new updates on this matter?

**Comment by aoberoi** [comment] 2020-06-03 00:00
The maintainers have decided to clearly mark this project no longer under active development. This project is not the recommended way to begin using the Slack platform using Python. Instead, we recommend using latest version of [Python SDK](https://slack.dev/python-slackclient) directly. We’ll still be around to address critical issues, and answer questions (and are working to be more responsive in these capacities than in the past).

I understand that not every use case is well addressed by the Python SDK today. We’re investing more energy than ever before to make Slack’s Python tooling as great as it can be. Come tell us about what matters to you so we can build the tools and libraries you want to use.

Thanks for keeping us honest and for being here.

**Comment by aoberoi** [comment] 2020-06-03 17:12
Even though the issue is closed, we still welcome further discussion.

**Closed as completed** 2020-06-03 17:11 UTC

**Comment by alindl** [comment] 2020-06-03 19:08
Are there any plans to work and improve on RTM in general? It seems like Slack is dragging it along, because the Events API isn't a full substitute. The whole shebang with the need for using a classic app is also not very encouraging, that it is here to stay, but maybe I'm just reading too much into that.

**Comment by aoberoi** [comment] 2020-09-25 22:44
@alindl fair question. at this time, there aren't any plans to improve the RTM API. that doesn't mean it will disappear and apps built on it will suddenly stop working. but it isn't where our team is focussed on making improvements.

i'd like to know where you see the Events API falling short. there's mainly two reasons people continue to chose the RTM API that i am aware of:
1) it works without starting a webserver, and without needing a publicly addressable URL with HTTPS. basically, its easier to set up.
2) the events API doesn't have a `user_typing` event, and you really want to make your bot look conversational, including imitating typing for a bit before your bot sends a message.

the first gap, we're working on a way to close. we'll have more to say about this in a few weeks.

the second gap, we aren't working on closing because we know from our user research that people prefer interactive apps most of the time over conversational bots. so we've been building features like App Home, Block Kit, and Modals to make bring those interactions to life. ultimately, if you want to pretend your bot is typing, you can do it by sending a "_@my_fun_bot is typing_" message from the app, and then removing it after you send your actual messge. better yet, you can send a spinner or other animation in an image.

anything else we should be aware of?

**Comment by aoberoi** [comment] 2020-09-25 22:46
its not all bad news: we're currently running a public beta of our next generation for Python tooling from Slack: [Bolt for Python](https://github.com/slackapi/bolt-python). 🎉

while it doesn't use RTM, it will be compatible with our solution for the first gap I alluded to above. we'd love your thoughts and feedback.

**Comment by CNG** [comment] 2020-09-25 22:57
I believe our use case falls squarely in Reason 1. Ease of setup is correct, though the hangup is not the setting up of a web server (the bot is already an app running on a server). The difficulty is we have a much higher burden to satisfy with regard to security reviews and infrastructure hardening for publicly exposed endpoints. I've thus far been able to get away with low overhead, quick iteration cycles because the bot using RTM is "just an internal app".

**Comment by alindl** [comment] 2020-09-28 10:08
@aoberoi You are maybe overestimating the need for ease of setting it up, as coughing up a webserver is really not that difficult, especially in Python. As @CNG correctly assumes, I don't want to have an unnecessary possible attack vector. My application doesn't run a webserver, so I don't want to have to work on hardening this one up, just for some Slack Bot. I eventually just wrote my own simple RTM-Bot by the way, as this was much easier than I thought.

Whatever you end up replacing RTM with, please consider that requirement.

**Comment by LukeHandle** [comment] 2020-11-30 19:16
Hi, to clarify @aoberoi:
> the first gap, we're working on a way to close. we'll have more to say about this in a few weeks.

^^ was this the bolt-python project, or were you looking at a better way for the apps to punch out the local Firewall vs. having to open up access in? Websockets seems like a pretty easy way to "solve" that, but I'm sure there's a reason you were wanting to move away from them...

(this being the concerns raised by @CNG / @alindl)

**Comment by stevengill** [comment] 2020-11-30 19:35
@LukeHandle nope. It is the upcoming [Socket Mode feature](https://medium.com/slack-developer-blog/product-developments-from-frontiers-47d7db535dc2#2d0a). It uses websockets under the hood. More details will be shared early in the new year. `bolt-python`, `bolt-js` & `bolt-java` will all support it.

**Comment by aoberoi** [comment] 2020-11-30 19:49
@LukeHandle thanks for the poke, I have more to say now. We announced "socket mode" at the beginning of October, during the Slack Frontiers conference. There's a blurb about socket mode in [this blog post](https://slack.com/blog/transformation/people-partners-systems-slack), and it will become available in early 2021.

How does this affect Python devs? You mostly guessed it - we implemented socket mode in [Bolt for Python](https://github.com/slackapi/bolt-python). Right now, Bolt will listen for HTTP requests on a specific path (e.g. `/slack/events`). But once socket mode is available you can simply update a bit of configuration and you wont need a web server at all. Bolt will connect to Slack over a WebSocket and the remaining application code should work the same.

So how is this different from RTM? Doesn't RTM already use WebSockets? The main problem with RTM never lied within the transport it used - WebSockets are a pretty good solution for many situations. Instead RTM's message protocol was built to communicate with user-facing Slack clients and that isn't a good solution for apps. The key differences in socket mode are: a single connection from an app will receive events from all workspaces where the app is installed (not just one), and each delivered message is expected to be acknowledged (so user-interactive features like buttons and menus can be served). There's lots of other interesting parts in this design, but these are the main differences.

While developers who've used RTM until this point are actually gaining quite a bit (access to huge platform features they never had before such as shortcuts, slash commands, App Home, granular bot permissions, interactive buttons, menus, date pickers and more), this new design also means your code needs to look different. The good news for most people who were using RTM is, since the functionality you have is pretty limited today, the migration path for those limited parts is relatively small and easy. But I'd really encourage you to re-imagine how you'd like your apps to work in the context of all the new platform features. For example, if you're using `process_message()` to parse an incoming message as some `command` followed by some `arguments...`, you're expecting your users to understand how command line programs work and to learn and memorize your command's syntax. Instead, you might allow the user to invoke a [Shortcut](https://api.slack.com/interactivity/shortcuts/using), which can display a menu of commands and a form to gather argument inputs. This can be much more intuitive for users who don't often run command line programs, or even users who do - but don't know much about your particular commands. Pro tip: you can still make the message based commands work for your power users too.

Ideally, the community interested in `python-rtmbot` can come help us improve [`bolt-python`](https://github.com/slackapi/bolt-python) and make it a stronger and more comprehensive framework. These two projects are essentially solving the same problems. The experience you all have, and the opinions you've formed about what makes a good framework for building Slack apps would be very valuable to share there.
