### ISSUE TITLE
Log Rotation for rtm-bot

### ISSUE THREAD

**Issue by pbdabholkar** [slackhq/python-rtmbot#92] opened 2018-04-17 13:09 UTC
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](../CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
> Please implement a way to configure daily / hourly log rotation for logging data. 

#### Reproducible in:
* [x] This is reproducible in the sample project.
RTMBot version: latest
Python version: 2.7
OS Version: MacOS High Sierra

#### Steps to reproduce:
> Not Applicable

### Expected result:
> Should be able to automatically create log files and rename the old log file accordingly. 
> Example Old log file format: rtmbot.log.2018.04.17

### Actual result:
> Functionality not available as of now.

**Comment by pbdabholkar** [comment] 2018-04-17 13:19
This issue is probably similar to https://github.com/slackapi/python-rtmbot/issues/66 but it doesn't have any specifics documented.

**Comment by Roach** [comment] 2018-05-29 23:21
I'd prefer to delegate logging to a general logger and add debug statements where they're valuable and leave the retention up to the implementing app's settings. Marking this as a duplicate of #66  and updating the contents of that request.

**Closed as completed by Roach** 2018-05-29 23:21 UTC
